# Generated by Django 5.2.8 on 2025-11-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicesession",
            name="is_settled",
            field=models.BooleanField(
                default=False,
                help_text="If True, balances for this session are finalized (e.g. Treasurer paid)",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive amount reduces debt (increases balance)",
                        max_digits=10,
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.player",
                    ),
                ),
            ],
        ),
    ]
